### ISSUE TITLE
No calendar + Unable to export data

### ISSUE THREAD

**Issue by Enissay** [FuzzyGrim/Yamtrack#507]
Hi all,

On a fresh docker+postgres instance, I managed to import my shows form Trakt, but I have a couple of issues:

1. I see one error, does it mean it still passed or the process was interrupted ?
![Image](https://github.com/user-attachments/assets/dbae5865-f82f-4dc8-8618-d5e9728e4b81)
 
2. My calendar in Trakt is almost full, here it is totally empty, what am I missing ?![Image](https://github.com/user-attachments/assets/01a53a61-c885-4ea1-88b6-924ed74d3524)

3. The app crashes and returns 499 code whenever I try to export my data! 
`10.0.1.98 - - [17/May/2025:15:10:23 +0200] "GET /export/csv?csrfmiddlewaretoken=p1l5x0ExwSk1yWAWAYWNzXFKclaK1pOAkxcIosFhtbWD6kNXB6pLXJpOmZqbe7gz HTTP/1.1" 499 0 "https://yamtrack.example.com/settings/export" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"`

Full debug log.
```
[2025-05-17 15:09:33 +0200] [61] [DEBUG] Language set to en
[2025-05-17 15:09:33 +0200] [61] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f325397cb80>
[2025-05-17 15:09:33 +0200] [61] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f325397cb80>
[2025-05-17 15:09:33 +0200] [61] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f325397cb80>
[2025-05-17 15:09:33 +0200] [61] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f325397cb80>
[2025-05-17 15:09:33 +0200] [61] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f325397cb80>
[2025-05-17 15:09:33 +0200] [61] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f325397cb80>
[2025-05-17 15:09:33 +0200] [61] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f325397cb80>
[2025-05-17 15:09:33 +0200] [61] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f325397cb80>
[2025-05-17 15:09:33 +0200] [61] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f325397cb80>
[2025-05-17 15:09:34 +0200] [61] [INFO] User enissay started CSV export
[2025-05-17 15:09:34 +0200] [61] [DEBUG] Streaming tvs to CSV
[2025-05-17 15:09:35 +0200] [33] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40b330>
[2025-05-17 15:09:35 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40b330>
[2025-05-17 15:09:35 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f2bce40b330>
[2025-05-17 15:09:35 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40b330>
[2025-05-17 15:09:35 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40b330>
[2025-05-17 15:09:35 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40b330>
[2025-05-17 15:09:35 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40b330>
[2025-05-17 15:09:36 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40b330>
[2025-05-17 15:09:36 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f2bce40b330>
[2025-05-17 15:09:36 +0200] [58] [DEBUG] Language set to en
[2025-05-17 15:09:36 +0200] [58] [DEBUG] Got redis://redis_app:6379/10 as the redis_url. Connecting to redis...
[2025-05-17 15:09:36 +0200] [58] [DEBUG] Attempting to connect to redis...
[2025-05-17 15:09:36 +0200] [58] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f3254ada7a0>
[2025-05-17 15:09:36 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f3254ada7a0>
[2025-05-17 15:09:36 +0200] [58] [DEBUG] Connection established. Redis is healthy.
[2025-05-17 15:09:36 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f3254ada7a0>
[2025-05-17 15:09:36 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f3254ada7a0>
[2025-05-17 15:09:36 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f3254ada7a0>
[2025-05-17 15:09:36 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f3254ada7a0>
[2025-05-17 15:09:36 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f3254ada7a0>
[2025-05-17 15:09:36 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f3254ada7a0>
[2025-05-17 15:09:36 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f3254ada7a0>
[2025-05-17 15:09:37 +0200] [58] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f3252eb7100>
[2025-05-17 15:09:37 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f3252eb7100>
[2025-05-17 15:09:37 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f3252eb7100>
[2025-05-17 15:09:37 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f3252eb7100>
[2025-05-17 15:09:37 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f3252eb7100>
[2025-05-17 15:09:37 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f3252eb7100>
[2025-05-17 15:09:37 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f3252eb7100>
[2025-05-17 15:09:37 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f3252eb7100>
[2025-05-17 15:09:37 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f3252eb7100>
[2025-05-17 15:09:41 +0200] [33] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40ad40>
[2025-05-17 15:09:41 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40ad40>
[2025-05-17 15:09:41 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f2bce40ad40>
[2025-05-17 15:09:41 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40ad40>
[2025-05-17 15:09:41 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40ad40>
[2025-05-17 15:09:41 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ad40>
[2025-05-17 15:09:41 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ad40>
[2025-05-17 15:09:41 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ad40>
[2025-05-17 15:09:41 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f2bce40ad40>
[2025-05-17 15:09:46 +0200] [33] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40ae30>
[2025-05-17 15:09:46 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40ae30>
[2025-05-17 15:09:46 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f2bce40ae30>
[2025-05-17 15:09:46 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40ae30>
[2025-05-17 15:09:46 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40ae30>
[2025-05-17 15:09:46 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ae30>
[2025-05-17 15:09:46 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ae30>
[2025-05-17 15:09:46 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ae30>
[2025-05-17 15:09:46 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f2bce40ae30>
[2025-05-17 15:09:51 +0200] [33] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40b330>
[2025-05-17 15:09:51 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40b330>
[2025-05-17 15:09:51 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f2bce40b330>
[2025-05-17 15:09:51 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40b330>
[2025-05-17 15:09:51 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40b330>
[2025-05-17 15:09:51 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40b330>
[2025-05-17 15:09:51 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40b330>
[2025-05-17 15:09:51 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40b330>
[2025-05-17 15:09:51 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f2bce40b330>
[2025-05-17 15:09:56 +0200] [33] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40ad40>
[2025-05-17 15:09:56 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40ad40>
[2025-05-17 15:09:56 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f2bce40ad40>
[2025-05-17 15:09:56 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40ad40>
[2025-05-17 15:09:56 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40ad40>
[2025-05-17 15:09:56 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ad40>
[2025-05-17 15:09:56 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ad40>
[2025-05-17 15:09:57 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ad40>
[2025-05-17 15:09:57 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f2bce40ad40>
[2025-05-17 15:10:02 +0200] [33] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40ae30>
[2025-05-17 15:10:02 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40ae30>
[2025-05-17 15:10:02 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f2bce40ae30>
[2025-05-17 15:10:02 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40ae30>
[2025-05-17 15:10:02 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40ae30>
[2025-05-17 15:10:02 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ae30>
[2025-05-17 15:10:02 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ae30>
[2025-05-17 15:10:02 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ae30>
[2025-05-17 15:10:02 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f2bce40ae30>
[2025-05-17 15:10:07 +0200] [33] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40b330>
[2025-05-17 15:10:07 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40b330>
[2025-05-17 15:10:07 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f2bce40b330>
[2025-05-17 15:10:07 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40b330>
[2025-05-17 15:10:07 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40b330>
[2025-05-17 15:10:07 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40b330>
[2025-05-17 15:10:07 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40b330>
[2025-05-17 15:10:07 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40b330>
[2025-05-17 15:10:07 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f2bce40b330>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] Got redis://redis_app:6379/10 as the redis_url. Connecting to redis...
[2025-05-17 15:10:08 +0200] [58] [DEBUG] Attempting to connect to redis...
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f32537c7fb0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f32537c7fb0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] Connection established. Redis is healthy.
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f32537c7fb0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f325375d9e0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f325375d9e0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f325375d9e0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f32537c7fb0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f32537c7fb0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f32537c7fb0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f32537c7fb0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f325375d9e0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f325375d9e0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f325375d9e0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f325375d9e0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f32537c7fb0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f325375d9e0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f32537c7fb0>
[2025-05-17 15:10:08 +0200] [58] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f325375d9e0>
[2025-05-17 15:10:12 +0200] [33] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40ad40>
[2025-05-17 15:10:12 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40ad40>
[2025-05-17 15:10:12 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f2bce40ad40>
[2025-05-17 15:10:13 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40ad40>
[2025-05-17 15:10:13 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40ad40>
[2025-05-17 15:10:13 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ad40>
[2025-05-17 15:10:13 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ad40>
[2025-05-17 15:10:13 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ad40>
[2025-05-17 15:10:13 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f2bce40ad40>
[2025-05-17 15:10:18 +0200] [33] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40ae30>
[2025-05-17 15:10:18 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40ae30>
[2025-05-17 15:10:18 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f2bce40ae30>
[2025-05-17 15:10:18 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40ae30>
[2025-05-17 15:10:18 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40ae30>
[2025-05-17 15:10:18 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ae30>
[2025-05-17 15:10:18 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ae30>
[2025-05-17 15:10:18 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ae30>
[2025-05-17 15:10:18 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f2bce40ae30>
[2025-05-17 15:10:23 +0200] [33] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40b330>
[2025-05-17 15:10:23 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40b330>
[2025-05-17 15:10:23 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f2bce40b330>
[2025-05-17 15:10:23 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40b330>
[2025-05-17 15:10:23 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40b330>
[2025-05-17 15:10:23 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40b330>
10.0.1.98 - - [17/May/2025:15:10:23 +0200] "GET /export/csv?csrfmiddlewaretoken=p1l5x0ExwSk1yWAWAYWNzXFKclaK1pOAkxcIosFhtbWD6kNXB6pLXJpOmZqbe7gz HTTP/1.1" 499 0 "https://yamtrack.example.com/settings/export" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"
[2025-05-17 15:10:23 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40b330>
[2025-05-17 15:10:23 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40b330>
[2025-05-17 15:10:23 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f2bce40b330>
[2025-05-17 15:10:28 +0200] [33] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40ad40>
[2025-05-17 15:10:28 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40ad40>
[2025-05-17 15:10:28 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f2bce40ad40>
[2025-05-17 15:10:28 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40ad40>
[2025-05-17 15:10:28 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40ad40>
[2025-05-17 15:10:28 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ad40>
[2025-05-17 15:10:28 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ad40>
[2025-05-17 15:10:28 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ad40>
[2025-05-17 15:10:28 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f2bce40ad40>
[2025-05-17 15:10:33 +0200] [33] [DEBUG] connection started: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40ae30>
[2025-05-17 15:10:33 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40ae30>
[2025-05-17 15:10:33 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [SSL_STARTUP] at 0x7f2bce40ae30>
[2025-05-17 15:10:33 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [STARTED] at 0x7f2bce40ae30>
[2025-05-17 15:10:33 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [MADE] at 0x7f2bce40ae30>
[2025-05-17 15:10:33 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ae30>
[2025-05-17 15:10:34 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ae30>
[2025-05-17 15:10:34 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [AWAITING_RESPONSE] at 0x7f2bce40ae30>
[2025-05-17 15:10:34 +0200] [33] [DEBUG] connection polled: <psycopg_binary.pq.PGconn [IDLE] (host=vps123.example.net port=7777 database=yamtrack) at 0x7f2bce40ae30>
```

**Comment by FuzzyGrim** [comment]
1. It imported everything except Friends S06E24.
2. It crashed while fetching media releases, fixed in the dev branch (https://github.com/FuzzyGrim/Yamtrack/commit/29330eb89b7ee7b81f9736735ae740a6bd1f749d).
3. Probably caused by (2).

**Comment by Enissay** [comment]
I tested the [dev image](https://github.com/FuzzyGrim/Yamtrack/pkgs/container/yamtrack/417827131?tag=dev), still the same issue.
I believe your commit from 5hrs ago was included there (last build 2hrs ago)...

**Comment by FuzzyGrim** [comment]
Would you mind sharing your Trakt slug? You can send it to [github@fuzzygrim.com](mailto:github@fuzzygrim.com) if you prefer.

**Comment by Enissay** [comment]
> Would you mind sharing your Trakt slug? You can send it to [github@fuzzygrim.com](mailto:github@fuzzygrim.com) if you prefer.

Sent!

EDIT:
Oh well, sending failed with `550 No such recipient here`.

Anyhow, here's my slug: **REACTED**

**Comment by FuzzyGrim** [comment]
Thanks, fixed the issue with the mail :sweat_smile:

I have imported your Trakt account with the dev image:

```
services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack:dev
```

And everything looks good to me.

![Image](https://github.com/user-attachments/assets/ceeb683a-9cab-4c6c-b0f1-648fb4590c87)

I'm not sure what Trakt shows in their calendar, but Yamtrack only shows media releases for the content you're tracking, I don't think you're currently watching anything that's currently airing.

If you go to /calendar?month=6&year=2023&view=grid you'll see it:

![Image](https://github.com/user-attachments/assets/aa0aaca4-d4ed-428b-982e-128d01e3503c)

**Comment by Enissay** [comment]
Here's my Trakt calendar starting today, and all these shows were successfully imported to Yamtrack:
![Image](https://github.com/user-attachments/assets/3027d9bb-a9e3-4987-a97f-e31b4fe2fd4c)

I have a question: how can I purge all data and do a fresh import ?
I know I could drop the DB and start over, but can it be also done through the GUI ?

**Comment by FuzzyGrim** [comment]
Fixed in dev.

![Image](https://github.com/user-attachments/assets/7016837d-9a63-49fc-b120-5981fd4017fc)

Previously, Yamtrack would only show, for example, The Last Of Us S02 episode releases if you have specifically added that season to your planning list. Whereas in Trakt, if you have the TV series in your planning list, it will show all season episodes in your calendar.

> I have a question: how can I purge all data and do a fresh import ?

At the moment this cannot be done through the GUI.

**Comment by Enissay** [comment]
I deleted the DB and started from scratch using dev image.
Finally import indeed completes, I got the same as you above.

When exporting, it indeed start but is super slow, my server has a 1gb connection!

![Image](https://github.com/user-attachments/assets/4d5e28fc-a6ee-4e10-814f-844de03ecd34)

Also, the output file doesnt seem to be complete as I get `500 error code` at the end:

![Image](https://github.com/user-attachments/assets/1618ead3-adb1-48a1-a303-bc0a285da830)

Log error:

```
[2025-05-17 23:08:22 +0200] [55] [DEBUG] Finished streaming tvs to CSV
[2025-05-17 23:08:22 +0200] [55] [DEBUG] Streaming seasons to CSV
...
[2025-05-17 23:08:55 +0200] [31] [CRITICAL] WORKER TIMEOUT (pid:55)
[2025-05-17 23:08:55 +0200] [55] [ERROR] Error handling request /export/csv?csrfmiddlewaretoken=zjsElWuykzYJMkZtemglkgupW8OTtKFeOc9SCwrxpk0hSVqB1Fcy0AHLEYsWijGk
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 240, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 182, in handle_request
    for item in respiter:
                ^^^^^^^^
  File "/yamtrack/integrations/exports.py", line 50, in generate_rows
    getattr(media, field, "") for field in fields["track"]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/app/models.py", line 1022, in progress
    sorted_episodes = sorted(
                      ^^^^^^^
  File "/yamtrack/app/models.py", line 1024, in <lambda>
    key=lambda e: e.item.episode_number,
                  ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 258, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 221, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1620, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 59, in cursor
    cursor = connection._djdt_cursor(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 21, in inner
    pass
  File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
10.0.1.98 - - [17/May/2025:23:08:55 +0200] "GET /export/csv?csrfmiddlewaretoken=zjsElWuykzYJMkZtemglkgupW8OTtKFeOc9SCwrxpk0hSVqB1Fcy0AHLEYsWijGk HTTP/1.1" 200 102804 "https://yamtrack.example.com/settings/export" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"

```

Calendar still empty though!
I wonder if these shows should have a specific status to show up there ?

**Comment by FuzzyGrim** [comment]
Could you show more logs?

If you see something like this:

> [2025-05-17 23:17:41 +0200] [284328] [INFO] 375892 - Using cached TVMaze episode map
[2025-05-17 23:17:41 +0200] [284328] [INFO] Solar Opposites S5 - TVDB ID found, fetching TVMaze episode data
[2025-05-17 23:17:41 +0200] [284328] [INFO] 375892 - Using cached TVMaze episode map
[2025-05-17 23:17:41 +0200] [284328] [INFO] Fetching releases for Elemental
[2025-05-17 23:17:41 +0200] [284328] [INFO] Processing TV show: Inside Job
[2025-05-17 23:17:41 +0200] [284328] [INFO] Inside Job - Processing 1 seasons (current season: None)
[2025-05-17 23:17:41 +0200] [284328] [INFO] Inside Job S1 - TVDB ID found, fetching TVMaze episode data

It means that it's still fetching episode releases. These are not imported from Trakt; it's a different task that starts after finishing the import from Trakt task. The first time to fetch episode releases will be slow (10-20 mins).

**Comment by Enissay** [comment]
Okay, I will let it work and try later, I will also disable DEBUG since it is too verbose.

One last thing regarding the calendar, I was trying to compare the shows that do show on the calendar, and those who dont, and it seems the ones with episodes count are showing, and those with 0 are not.
The it could be what you said.
I will give it time and check again tomorrow

![Image](https://github.com/user-attachments/assets/623ba12c-9aa5-4a67-b24b-8009f7db2626)

**Comment by Enissay** [comment]
My observation was quite correct, I now see all shows were loaded and the calendar finally filled!

![Image](https://github.com/user-attachments/assets/5692ad86-184c-4ba4-82ec-134061c7afc2)

The export however still breaks:
```
[2025-05-18 22:50:03 +0200] [57] [INFO] User enissay started CSV export
[2025-05-18 22:52:52 +0200] [32] [INFO] Scheduler: Sending due task send_release_notifications (Send release notifications)
[2025-05-18 22:52:53 +0200] [31] [INFO] Task Send release notifications[e3c723c3-6700-49b0-b32f-5c4d21851c91] received
[2025-05-18 22:52:53 +0200] [29525] [INFO] Starting recent release notification task
[2025-05-18 22:52:53 +0200] [29525] [INFO] Task Send release notifications[e3c723c3-6700-49b0-b32f-5c4d21851c91] succeeded in 0.33580373390577734s: 'No recent releases found'
[2025-05-18 22:53:24 +0200] [30] [CRITICAL] WORKER TIMEOUT (pid:57)
[2025-05-18 22:53:24 +0200] [57] [ERROR] Error handling request /export/csv?csrfmiddlewaretoken=Idao8HVqoSKj0dn4p3ImC7UGtwrMQFgWOCYimAjxZe2gSOtDPKKWYo4j2gDEEFhk
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 240, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 182, in handle_request
    for item in respiter:
                ^^^^^^^^
  File "/yamtrack/integrations/exports.py", line 50, in generate_rows
    getattr(media, field, "") for field in fields["track"]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yamtrack/app/models.py", line 1022, in progress
    sorted_episodes = sorted(
                      ^^^^^^^
  File "/yamtrack/app/models.py", line 1024, in <lambda>
    key=lambda e: e.item.episode_number,
                  ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 258, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 221, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/cursor.py", line 93, in execute
    self._conn.wait(
  File "/usr/local/lib/python3.12/site-packages/psycopg/connection.py", line 406, in wait
    return waiting.wait(gen, self.pgconn.socket, interval=interval)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "psycopg_binary/_psycopg/waiting.pyx", line 201, in psycopg_binary._psycopg.wait_c
  File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
10.0.1.98 - - [18/May/2025:22:53:24 +0200] "GET /export/csv?csrfmiddlewaretoken=Idao8HVqoSKj0dn4p3ImC7UGtwrMQFgWOCYimAjxZe2gSOtDPKKWYo4j2gDEEFhk HTTP/1.1" 200 110728 "https://yamtrack.example.com/settings/export" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"
[2025-05-18 22:53:24 +0200] [57] [INFO] Worker exiting (pid: 57)
[2025-05-18 22:53:25 +0200] [30] [ERROR] Worker (pid:57) was sent SIGKILL! Perhaps out of memory?
[2025-05-18 22:53:25 +0200] [29779] [INFO] Booting worker with pid: 29779
2025-05-18 22:57:40,762 INFO reaped unknown pid 29859 (terminated by SIGPIPE)
[2025-05-18 23:02:53 +0200] [32] [INFO] Scheduler: Sending due task send_release_notifications (Send release notifications)
[2025-05-18 23:02:53 +0200] [31] [INFO] Task Send release notifications[38a17067-b365-472d-95ed-9a0f4b1774db] received
[2025-05-18 23:02:53 +0200] [29766] [INFO] Starting recent release notification task
[2025-05-18 23:02:53 +0200] [29766] [INFO] Task Send release notifications[38a17067-b365-472d-95ed-9a0f4b1774db] succeeded in 0.548888481920585s: 'No recent releases found'

```

**Comment by FuzzyGrim** [comment]
> The export however still breaks:

I have made some changes in `dev`, could you pull the updated image and check if it works?

**Comment by FuzzyGrim** [comment]
Fixed in [v0.23.0](https://github.com/FuzzyGrim/Yamtrack/releases/tag/v0.23.0)

**Comment by Enissay** [comment]
Sorry I missed your comment.
I just deployed v0.23.1, everything loaded very fast including the calendar.
The export was super fast with no errors
Thank you very much for the responsiveness <3
