### ISSUE TITLE
[BUG] Graph don't show automatic/imported logs properly

### ISSUE THREAD

**Issue by JacobDB** [FuzzyGrim/Yamtrack#576]
**Describe the bug**
Under "Statistics," there's a Github-like graph showing you how much of what you watched on which days. This seems to work well when I manually mark something in the web app, but when things are automatically logged via the webhook from my Jellyfin server, this doesn't seem to affect the graph. Additionally, all of my imported Trakt history shows on a single day, the day of the import, even though the dates are showing properly as I scroll through my "Media Timeline."

**To Reproduce**
Import data from Trakt, or set up automatic logging via Jellyfin. Observe the incorrect data in the graph.

**Expected behavior**
The graph should show all of the correct dates, as they appear under "Media Timeline."

**Screenshots**

![Image](https://github.com/user-attachments/assets/f3ea4e63-e8e8-4f37-8a0c-2115e37a88db)

![Image](https://github.com/user-attachments/assets/60e1ee45-b39b-42da-b181-ae94e06f18f2)

**Error logs**
N/A

**Yamtrack version**: v0.23.1
**Database**: SQLite

**Comment by FuzzyGrim** [comment]
Fixed in [v0.24.0](https://github.com/FuzzyGrim/Yamtrack/releases/tag/v0.24.0).

**Comment by JacobDB** [comment]
Webhook logging is now showing appropriately in the statistics, but my original import from Trakt still shows everything on a single day, despite there being dates associated to these logs. Others seem to be experiencing this too, i.e. #665

**Comment by FuzzyGrim** [comment]
The timeline and activity history dates are different things, the timeline tracks your watch history while the activity history tracks your usage of Yamtrack.

But in `v0.24.0` I updated the imports from external sites to also import the usage in those sites, to fix your activity history you will need to import again from Trakt with the Sync New Items and Overwrite Existing option. It will overwrite all TV Show and Movie progress to match the ones in Trakt though.

![Image](https://github.com/user-attachments/assets/c798b586-bc41-4860-b10c-0b087c91e0e1)

The issue you linked is different, it's about movies not appearing in the timeline...
