### ISSUE TITLE
[BUG] Completion Status for Ongoing Series (Comics)

### ISSUE THREAD

**Issue by chr-lucas** [FuzzyGrim/Yamtrack#735]
**Describe the bug**
When updating status of an ongoing series (comics) to the most currently released issue, status is automatically set to "Complete". When a new issue is released, and metadata updated, the status persists as "Complete" even though there are new unconsumed issues.

**To Reproduce**

1. Set Progress (Issues) to currently released issue number.
2. Review progress after a new issue has released.
3. Status will still be set as "Complete".

**Expected behavior**
A series set to "Complete" would revert to "In Progress" when the Progress (Issues) count is less than total number of released issues.

**Screenshots**

<img width="112" height="351" alt="Progress doesn't align with issue count" src="https://github.com/user-attachments/assets/543e5c49-1847-485a-806d-98774c8d0589" />

**Yamtrack version**: v0.24.6
**Database**: SQLite

**Comment by east35** [comment]
Has there been any movement on this? This small bug is the only issue in my personal experience.

**Comment by FuzzyGrim** [comment]
Should be fixed in the latest release

**Comment by east35** [comment]
I'm still experiencing this issue on v0.24.9. The problem appears to be that the system doesn't distinguish between "all current issues read" and "series actually complete." 

**Example scenario:**
- A comic series has only 3 issues published so far (but is ongoing)
- I mark issue 3 as read
- Yamtrack marks the entire series as "Complete"
- This is incorrect because the series is ongoing and will have more issues

Root cause: The data source doesn't indicate when/if a series will end. So even if a series only has 3 issues currently in print but could hypothetically have 100+ issues in its lifetime, marking issue #3 as read causes the whole series to be marked as complete when it's really not. 

**Expected behavior**: For ongoing series, the status should be "In Progress" or "Up to Date" rather than "Complete" until the series actually ends. The app needs to distinguish between:

- "Complete" = Series ended AND all issues read
- "Up to Date" = All currently published issues read, but series ongoing

Is there a way to track whether a series is ongoing vs. completed in the metadata source?

**Comment by FuzzyGrim** [comment]
The metadata provider (ComicVine) doesn't track whether a comic is ongoing or completed. What I did in the previous fix was simply not automatically set the "Completed" option for comics when marking issues as read. The user will have to manually mark something as completed.

Could you try again? Perhaps it didn't work when you tried it right after the update due to the caching system.
